#!/bin/bash

# get all colors
color_list=$(.theos/obj/debug/uicolorutil | grep -v "(null)")

declare -A colors

# put colors
while IFS= read -r col; do
	name=${col%% *}
	name=${name//#/}
	value=${col##* }
	value=${value//#/}
	value="${value,,}" # lowercase !!
	#echo "$name => $value hi: ${colors[$value]}"
	if [[ -v colors[$value] ]]; then
		# color known, add it to the value
		colors[$value]="${colors[$value]} $name"
	else
		# color unknown, add it to the map
		colors[$value]="$name"
	fi
done <<< "$color_list"

#for hex in "${!colors[@]}"; do
#	printf "%s=%s\n" "$hex" "${colors[$hex]}"
#done

# cursed codegen
source mocha.sh

outfile="ctpios-gen/Tweak.x"

read -r -d '' fileheader << MEOWMEOW
/*
* THIS FILE IS AUTOGENERATED BY sort_colors.sh !!
* DO NOT EDIT MANUALLY, YOUR CHANGES WILL BE OVERRIDDEN
*/

#import <UIKit/UIKit.h>
#import <UIKit/UIColor.h>

#define UIColorFromRGB(rgbValue) [UIColor colorWithRed:((float)((rgbValue & 0xFF0000) >> 16))/255.0 green:((float)((rgbValue & 0xFF00) >> 8))/255.0 blue:((float)(rgbValue & 0xFF))/255.0 alpha:1.0]

%hook UIColor
MEOWMEOW

echo "$fileheader" > $outfile

for hex in "${!colors[@]}"; do
	if [[ -v mappings[$hex] ]]; then
		repl=${mappings[$hex]}
		names=${colors[$hex]}
		names=($names)
		for name in "${names[@]}"; do
			echo "+(id)${name} { return UIColorFromRGB(0x$repl); }" >> $outfile
		done
		#printf "%s=%s\n" "$hex" "${colors[$hex]}"
	else
		echo "warning: no mapping found for $hex"
	fi
done

echo "%end" >> $outfile
