#!/bin/bash

#UICOLOR_FILE=UIColor_custom.h
UICOLOR_FILE=UIColor.h
# read UIColor.h and also remove general "junk"
methods_tmp=$(grep -v '^*\|^/\*\|^#import\|^@property\|^@class\|^@end\|^@interface \|^}\|^[[:space:]]*NSString\*' $UICOLOR_FILE | sed 's/^+ /+/g' | sed 's/^- /-/g')
# remove unwanted functions (initializers, functions that return void or BOOL, etc)
methods_tmp=$(echo "$methods_tmp" | grep -Ev "^[+-]\(BOOL|void|unsigned long|Class|NSString \*|double|NSArray \*\)")
# remove unwanted functions (wip, doesn't filter everything yet)
methods_tmp=$(echo "$methods_tmp" | grep -Ev "^[+-]\(.*\)(resolvedColorWith|init|copy|_debug|loadDataWith|_colorBlendedWith|colorNamed|_dynamicCatalog|alloc|_apiColorNames|(read|writ)able|_disambiguated_due_to_CIImage|(CG|cg)Color;|classFallbacks|colorSpaceName|styleString)")
#echo "$methods_tmp"
# TEMPORARILY: remove functions that take arguments or don't return (id) (until we can/need to work with them)
methods_tmp=$(echo "$methods_tmp" | grep -E "^[+-]\(id\)" | grep -v ":\|)arg1")
# VERY TEMPORARILY REMOVE THIS SOMETIME WHEN FIXED remove _ functions
methods_tmp=$(echo "$methods_tmp" | grep -Ev "^[+-]\(.*\)(_)")
# nuke empty lines
methods_tmp=$(echo "$methods_tmp" | sed '/^[[:space:]]*$/d')
# extract the method names
method_names=$(echo "$methods_tmp" | sed 's/[^)]*)//' | sed 's/;.*$//')
#echo "$method_names"
# put method names in a funny file that we can include and run :3c

read -r -d '' fileheader << MEOWMEOW
/*
* THIS FILE IS AUTOGENERATED BY get_methods.sh !!
* DO NOT EDIT MANUALLY, YOUR CHANGES WILL BE OVERRIDDEN
*/

#import "UIColor+Utility.m"
#import "tools/UIColor.h"

#define NSPrintf(...)   printf( "%s", [[NSString stringWithFormat: __VA_ARGS__] UTF8String] )

#define printColor(method, color)   NSPrintf(@"%s %@\n", method, [color representInHex])

void printAllColorsMeow() {
MEOWMEOW

outfile="./../gen.m"

echo "$fileheader" > "$outfile"

while IFS= read -r method; do
    echo "	printColor(\"${method}\", [UIColor ${method}]);" >> "$outfile"
    #echo "	NSLog(@\"${method} -> %@\", [[UIColor ${method}] representInHex]);" >> "$outfile"
    #echo "	NSLog(@\"${method} -> %@\", [UIColor ${method}]);" >> "$outfile"
done <<< "$method_names"

echo "}" >> "$outfile"
